FROM cyan/raonosdemo-base

WORKDIR /bp2/src/

EXPOSE 22
EXPOSE 8080

ENV NBI_raonosdemosim_port=22
ENV NBI_raonosdemosim_publish=True
ENV NBI_rasim_port=22
ENV NBI_rasim_typeGroup=SAM
ENV NBI_rasim_username=security
ENV NBI_rasim_password=security
ENV NBI_rasim_publish=True
